# fly.toml app configuration file for gtm-ai-tools
# Generated on 2025-06-11T08:15:57Z
# Reference: https://fly.io/docs/reference/configuration/

app = "gtm-ai-tools"
primary_region = "iad"

[build]
# Specify Dockerfile path or builder here if needed
# Example: dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "gtm_data"
  destination = "/data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
