version: '3'

vars:
  IMAGE: gtm-ai-tools

silent: false

tasks:
  git:pull:
    cmds:
      - git pull

  docker:build:
    cmds:
      - docker build -t {{.IMAGE}} .

  run:command:
    desc: Run a utility inside the Docker image and capture output
    cmds:
      - mkdir -p output
      - |
          set -e
          set -- {{.CLI_ARGS}}
          cmd="$1"
          shift
          echo Running: docker run --env-file .env -v $(pwd)/output:/workspace {{.IMAGE}} python utils/${cmd}.py "$@"
          docker run --env-file .env -v $(pwd)/output:/workspace {{.IMAGE}} python utils/${cmd}.py "$@" 2>&1 | tee output/run.log
      - mkdir -p /tmp/outputs
      - cp -a output/* /tmp/outputs/ 2>/dev/null || true
